package commandmeta

// Command relationships for "See also" cross-references.
// Key format: "command" for root commands, "command.subcommand" for subcommands.
var commandRelationships = map[string][]string{
	// P0: High confusion command pairs
	"doctor": {"workspace doctor", "plan doctor"},
	"run":    {"tasks", "events", "sessions"},
}

var subcommandRelationships = map[string][]string{
	// P0: Task workflow confusion
	"tasks.take":  {"run --take", "tasks next", "tasks renew"},
	"tasks.claim": {"tasks take", "tasks renew"},

	// P0: Workspace diagnostics
	"workspace.doctor": {"doctor", "plan doctor"},

	// P0: Session restoration confusion
	"sessions.restore-plan": {"sessions resume-plan", "run"},
	"sessions.resume-plan":  {"sessions restore-plan", "sessions replay", "run --take"},
	"sessions.replay":       {"sessions resume-plan", "sessions restore-plan", "run"},
}

var rootCommands = []Command{
	{Name: "init", Description: "initialize ADP home", Usage: []string{"adp init"}},
	{
		Name:        "quickstart",
		Description: "interactive setup for new users",
		Usage:       []string{"adp quickstart [--non-interactive] [--adp-home <path>] [--workspace-name <name>] [--project-root <path>] [--memory] [--mcp] [--agents]"},
		Options: describedValues(valueDescriptions{
			"--non-interactive": "skip interactive prompts",
			"--adp-home":        "ADP home directory path",
			"--workspace-name":  "workspace name",
			"--project-root":    "project root directory",
			"--memory":          "enable memory",
			"--mcp":             "enable MCP servers",
			"--agents":          "enable custom agents",
		}, "--non-interactive", "--adp-home", "--workspace-name", "--project-root", "--memory", "--mcp", "--agents"),
	},
	{
		Name:        "doctor",
		Description: "diagnose registered workspaces",
		Usage:       []string{"adp doctor [workspace] [--verbose] [--format <text|json>]"},
		Options: describedValues(valueDescriptions{
			"--verbose": "show info diagnostics",
			"--format":  "output format",
		}, "--verbose", "--format"),
	},
	{Name: "version", Description: "print version information", Usage: []string{"adp version"}},
	{
		Name:        "workspace",
		Description: "manage registered workspaces",
		Usage: []string{
			"adp workspace add <name> <project-root>",
			"adp workspace list",
			"adp workspace show <name>",
			"adp workspace remove <name>",
			"adp workspace rename <old-name> <new-name>",
			"adp workspace doctor [name] [--verbose] [--format <text|json>]",
		},
		Subcommands: describedValues(valueDescriptions{
			"add":    "register a project root",
			"list":   "list registered workspaces",
			"show":   "show one workspace",
			"remove": "remove workspace registration",
			"rename": "rename workspace registration",
			"doctor": "diagnose workspace config",
		}, "add", "list", "show", "remove", "rename", "doctor"),
		Options: describedValues(valueDescriptions{
			"--verbose": "show info diagnostics",
			"--format":  "output format",
		}, "--verbose", "--format"),
	},
	{
		Name:        "enter",
		Description: "enter a kept runtime shell",
		Usage:       []string{"adp enter <workspace> [--keep-runtime]"},
		Options:     describedValues(valueDescriptions{"--keep-runtime": "keep runtime directory after shell exits"}, "--keep-runtime"),
	},
	{
		Name:        "env",
		Description: "render runtime environment exports",
		Usage:       []string{"adp env <workspace> [--cd]"},
		Options:     describedValues(valueDescriptions{"--cd": "change directory to runtime root"}, "--cd"),
	},
	{
		Name:        "shell-hook",
		Description: "render shell helper function",
		Usage:       []string{"adp shell-hook [--shell <sh|bash|zsh>] [--name <function-name>]"},
		Options: describedValues(valueDescriptions{
			"--shell":    "render for shell",
			"-s":         "render for shell",
			"--name":     "function name",
			"--function": "function name",
			"-n":         "function name",
		}, "--shell", "-s", "--name", "--function", "-n"),
	},
	{
		Name:        "completion",
		Description: "render shell completion script",
		Usage: []string{
			"adp completion [--shell <bash|zsh>] [--command <name>]",
			"adp completion values <agents|workspaces|profiles|tasks|phases|sessions|owners|statuses> [--workspace <name>]",
		},
		Subcommands: describedValues(valueDescriptions{"values": "print dynamic completion values"}, "values"),
		Options: describedValues(valueDescriptions{
			"--shell":     "render for shell",
			"-s":          "render for shell",
			"--command":   "command name",
			"--workspace": "workspace name",
			"-w":          "workspace name",
		}, "--shell", "-s", "--command", "--workspace", "-w"),
	},
	{
		Name:        "events",
		Description: "read ADP event logs",
		Usage:       []string{"adp events list [--workspace <name>] [--session <session-id>] [--task <task-id>] [--type <event-type>] [--limit <n>] [--format <text|json>]"},
		Subcommands: describedValues(valueDescriptions{"list": "list runtime events"}, "list"),
		Options: describedValues(valueDescriptions{
			"--workspace": "filter by workspace",
			"-w":          "filter by workspace",
			"--session":   "filter by session",
			"--task":      "filter by task",
			"--type":      "filter by event type",
			"--limit":     "limit result count",
			"--format":    "output format",
		}, "--workspace", "-w", "--session", "--task", "--type", "--limit", "--format"),
	},
	{
		Name:        "sessions",
		Description: "summarize ADP session history",
		Usage: []string{
			"adp sessions list [--workspace <name>] [--agent <agent>] [--task <task-id>] [--limit <n>] [--format <text|json>]",
			"adp sessions show <session-id> [--format <text|json>]",
			"adp sessions restore-plan <session-id> [--format <text|json>]",
			"adp sessions resume-plan <session-id> [--workspace <name>] [--owner <owner>] [--lease <duration>] [--agent <agent>] [--format <text|json>]",
			"adp sessions replay <session-id> --dry-run [--workspace <name>] [--owner <owner>] [--lease <duration>] [--agent <agent>] [--format <text|json>]",
		},
		Subcommands: describedValues(valueDescriptions{
			"list":         "list runtime sessions",
			"show":         "show one session",
			"restore-plan": "print read-only rerun guidance",
			"resume-plan":  "print read-only cross-tool resume guidance",
			"replay":       "dry-run local replay preflight",
		}, "list", "show", "restore-plan", "resume-plan", "replay"),
		Options: describedValues(valueDescriptions{
			"--workspace": "filter by workspace",
			"-w":          "filter by workspace",
			"--agent":     "agent filter or resume target",
			"--task":      "filter by task",
			"--limit":     "limit result count",
			"--owner":     "task owner",
			"--lease":     "ownership lease duration",
			"--dry-run":   "print replay preflight without executing",
			"--format":    "output format",
		}, "--workspace", "-w", "--agent", "--task", "--limit", "--owner", "--lease", "--dry-run", "--format"),
	},
	{
		Name:        "runtime",
		Description: "manage ADP runtime directories",
		Usage:       []string{"adp runtime prune [--older-than <duration>] [--include-kept] [--dry-run] [--yes] [--format <text|json>]"},
		Subcommands: describedValues(valueDescriptions{"prune": "delete stale ADP-owned runtimes"}, "prune"),
		Options: describedValues(valueDescriptions{
			"--older-than":   "minimum runtime age",
			"--include-kept": "include kept runtimes",
			"--dry-run":      "print candidates without deleting",
			"--yes":          "skip confirmation prompts",
			"-y":             "skip confirmation prompts",
			"--format":       "output format",
		}, "--older-than", "--include-kept", "--dry-run", "--yes", "-y", "--format"),
	},
	{
		Name:        "tasks",
		Description: "manage the local workspace task board",
		Usage: []string{
			"adp tasks add [--workspace <name>] [--priority <value>] [--phase <value>] [--description <text>] <title>",
			"adp tasks list [--workspace <name>] [--format <text|json>]",
			"adp tasks next [--workspace <name>] [--limit <n>] [--format <text|json>]",
			"adp tasks take [--workspace <name>] --owner <owner> [--lease <duration>] [--format <text|json>]",
			"adp tasks stale [--workspace <name>] [--format <text|json>]",
			"adp tasks show [--workspace <name>] <task-id> [--format <text|json>]",
			"adp tasks update [--workspace <name>] <task-id> --status <planned|ready|in_progress|blocked|review|validated|done|canceled>",
			"adp tasks claim [--workspace <name>] <task-id> --owner <owner> [--lease <duration>]",
			"adp tasks renew [--workspace <name>] <task-id> --owner <owner> --lease <duration>",
			"adp tasks release [--workspace <name>] <task-id> [--owner <owner>]",
			"adp tasks done [--workspace <name>] <task-id>",
			"adp tasks block [--workspace <name>] <task-id> --reason <reason>",
		},
		Subcommands: describedValues(valueDescriptions{
			"add":     "add a task to the board",
			"list":    "list tasks",
			"next":    "preview next claimable work",
			"take":    "atomically claim next work",
			"stale":   "inspect expired in-progress claims",
			"show":    "show one task",
			"update":  "set task status",
			"claim":   "claim a selected task",
			"renew":   "extend an owned task lease",
			"release": "release a claim",
			"done":    "mark a task done",
			"block":   "mark a task blocked",
		}, "add", "list", "next", "take", "stale", "show", "update", "claim", "renew", "release", "done", "block"),
		Options: describedValues(valueDescriptions{
			"--workspace":   "workspace name",
			"-w":            "workspace name",
			"--priority":    "task priority",
			"--phase":       "task phase",
			"--description": "task description",
			"--status":      "task status",
			"--reason":      "blocked reason",
			"--owner":       "task owner",
			"--lease":       "claim lease duration",
			"--limit":       "result limit",
			"--format":      "output format",
		}, "--workspace", "-w", "--priority", "--phase", "--description", "--status", "--reason", "--owner", "--lease", "--limit", "--format"),
	},
	{
		Name:        "plan",
		Description: "preview, apply, or diagnose local planning state",
		Usage: []string{
			"adp plan preview [--workspace <name>] --file <path|-> [--format <text|json>]",
			"adp plan apply [--workspace <name>] --file <path|-> [--format <text|json>]",
			"adp plan doctor [--workspace <name>] [--format <text|json>]",
		},
		Subcommands: describedValues(valueDescriptions{
			"preview": "validate plan input without writing",
			"apply":   "write validated plan input",
			"doctor":  "diagnose local planning ledger",
		}, "preview", "apply", "doctor"),
		Options: describedValues(valueDescriptions{
			"--workspace": "workspace name",
			"-w":          "workspace name",
			"--file":      "structured plan input path",
			"-f":          "structured plan input path",
			"--format":    "output format",
		}, "--workspace", "-w", "--file", "-f", "--format"),
	},
	{
		Name:        "phase",
		Description: "manage workspace phase gates",
		Usage: []string{
			"adp phase add [--workspace <name>] [--goal <text>] <phase-id> <title>",
			"adp phase list [--workspace <name>] [--format <text|json>]",
			"adp phase show [--workspace <name>] <phase-id> [--format <text|json>]",
			"adp phase status [--workspace <name>] [--format <text|json>]",
			"adp phase start [--workspace <name>] <phase-id>",
			"adp phase accept [--workspace <name>] <phase-id> [--command <cmd>] [--result <result>] [--notes <text>]",
			"adp phase commit [--workspace <name>] <phase-id> --hash <commit-hash> [--message <text>]",
			"adp phase push [--workspace <name>] <phase-id> --remote <remote> --branch <branch> [--result <result>]",
		},
		Subcommands: describedValues(valueDescriptions{
			"add":    "add a phase",
			"list":   "list phases",
			"show":   "show one phase",
			"status": "show next gate action",
			"start":  "start the next planned phase",
			"accept": "record validation evidence",
			"commit": "record commit evidence",
			"push":   "record push evidence",
		}, "add", "list", "show", "status", "start", "accept", "commit", "push"),
		Options: describedValues(valueDescriptions{
			"--workspace": "workspace name",
			"-w":          "workspace name",
			"--goal":      "phase goal",
			"--command":   "acceptance command",
			"--result":    "gate result",
			"--notes":     "gate notes",
			"--hash":      "commit hash",
			"--message":   "commit message",
			"--remote":    "push remote",
			"--branch":    "push branch",
			"--format":    "output format",
		}, "--workspace", "-w", "--goal", "--command", "--result", "--notes", "--hash", "--message", "--remote", "--branch", "--format"),
	},
	{
		Name:        "progress",
		Description: "summarize workspace execution progress",
		Usage: []string{
			"adp progress [--workspace <name>] [--format <text|json>]",
			"adp progress report [--workspace <name>] [--language <en|zh-CN>] [--format <markdown|json>]",
		},
		Subcommands: describedValues(valueDescriptions{"report": "render progress report"}, "report"),
		Options: describedValues(valueDescriptions{
			"--workspace": "workspace name",
			"-w":          "workspace name",
			"--format":    "output format",
			"--language":  "report language",
		}, "--workspace", "-w", "--format", "--language"),
	},
	{
		Name:        "run",
		Description: "run an agent inside a runtime",
		Usage:       []string{"adp run <agent> [--workspace <name>] [--profile <profile>] [--task <task-id>|--take --owner <owner> [--lease <duration>]] [--keep-runtime] [-- <agent-args>...]"},
		Options: describedValues(valueDescriptions{
			"--workspace":    "workspace name",
			"-w":             "workspace name",
			"--profile":      "profile name",
			"-p":             "profile name",
			"--task":         "task id",
			"--take":         "atomically take next task before launch",
			"--owner":        "task owner",
			"--lease":        "claim lease duration",
			"--keep-runtime": "keep runtime directory",
			"--":             "pass following args to agent",
		}, "--workspace", "-w", "--profile", "-p", "--task", "--take", "--owner", "--lease", "--keep-runtime", "--"),
	},
}
