package shared

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/karoc/adp/internal/adapters/api"
	"github.com/karoc/adp/internal/gitenv"
)

func Instructions(adapterName string, ctx api.Context) []byte {
	var b strings.Builder
	title := strings.ToUpper(adapterName[:1]) + adapterName[1:]

	fmt.Fprintf(&b, "# ADP Runtime Instructions for %s\n\n", title)
	b.WriteString("This file was generated by ADP for the current runtime session.\n")
	b.WriteString("Project source files remain separate from ADP workspace configuration.\n\n")

	writeWorkspace(&b, adapterName, ctx)
	writeTask(&b, ctx)
	writePlanningContract(&b, ctx)
	writeLeaseHandoff(&b, ctx)
	writeGitBoundary(&b, ctx)
	writeTaskboxBridge(&b, ctx)
	writePlanModeBridge(&b, ctx)
	writeSection(&b, "Base Prompt", readWorkspaceFile(ctx.WorkspaceDir, ctx.Config.Prompts.Base, "No base prompt is configured."))
	writeSection(&b, "Shared Memory", memoryText(ctx))
	writeSection(&b, "Rules", rulesText(ctx))
	writeSection(&b, "MCP", mcpText(ctx))
	writeSection(&b, "Profile", profileText(adapterName, ctx))

	return []byte(b.String())
}

func MetadataTOML(adapterName string, ctx api.Context) []byte {
	var b strings.Builder
	b.WriteString("# Generated by ADP for the current runtime session.\n")
	b.WriteString("[adp]\n")
	fmt.Fprintf(&b, "adapter = %s\n", quote(ctxString(adapterName)))
	fmt.Fprintf(&b, "workspace = %s\n", quote(ctx.Config.Workspace.Name))
	fmt.Fprintf(&b, "project_root = %s\n", quote(ctx.Config.Project.Root))
	fmt.Fprintf(&b, "git_root = %s\n", quote(ctx.GitRoot))
	fmt.Fprintf(&b, "profile = %s\n", quote(EffectiveProfile(ctx)))
	fmt.Fprintf(&b, "memory_enabled = %t\n", ctx.Config.Memory.Enabled)
	fmt.Fprintf(&b, "mcp_enabled = %t\n", ctx.Config.MCP.Enabled)
	if !ctx.Task.IsZero() {
		fmt.Fprintf(&b, "task_id = %s\n", quote(ctx.Task.ID))
		fmt.Fprintf(&b, "task_title = %s\n", quote(ctx.Task.Title))
		fmt.Fprintf(&b, "task_status = %s\n", quote(ctx.Task.Status))
		fmt.Fprintf(&b, "task_priority = %s\n", quote(ctx.Task.Priority))
		fmt.Fprintf(&b, "task_phase = %s\n", quote(ctx.Task.Phase))
		if strings.TrimSpace(ctx.Task.Owner) != "" {
			fmt.Fprintf(&b, "task_owner = %s\n", quote(ctx.Task.Owner))
		}
		if !ctx.Task.ClaimedAt.IsZero() {
			fmt.Fprintf(&b, "task_claimed_at = %s\n", quote(formatTaskTime(ctx.Task.ClaimedAt)))
		}
		if !ctx.Task.LeaseExpiresAt.IsZero() {
			fmt.Fprintf(&b, "task_lease_expires_at = %s\n", quote(formatTaskTime(ctx.Task.LeaseExpiresAt)))
		}
	}
	return []byte(b.String())
}

func MetadataJSON(adapterName string, ctx api.Context) ([]byte, error) {
	adp := map[string]any{
		"adapter":       adapterName,
		"workspace":     ctx.Config.Workspace.Name,
		"projectRoot":   ctx.Config.Project.Root,
		"gitRoot":       ctx.GitRoot,
		"profile":       EffectiveProfile(ctx),
		"memoryEnabled": ctx.Config.Memory.Enabled,
		"mcpEnabled":    ctx.Config.MCP.Enabled,
	}
	if !ctx.Task.IsZero() {
		task := map[string]any{
			"id":       ctx.Task.ID,
			"title":    ctx.Task.Title,
			"status":   ctx.Task.Status,
			"priority": ctx.Task.Priority,
			"phase":    ctx.Task.Phase,
		}
		if strings.TrimSpace(ctx.Task.Owner) != "" {
			task["owner"] = ctx.Task.Owner
		}
		if !ctx.Task.ClaimedAt.IsZero() {
			task["claimedAt"] = formatTaskTime(ctx.Task.ClaimedAt)
		}
		if !ctx.Task.LeaseExpiresAt.IsZero() {
			task["leaseExpiresAt"] = formatTaskTime(ctx.Task.LeaseExpiresAt)
		}
		adp["task"] = task
	}
	data := map[string]any{
		"adp": adp,
	}
	return json.MarshalIndent(data, "", "  ")
}

func RenderEnv(adapterName string, ctx api.Context) map[string]string {
	env := map[string]string{
		"ADP_AGENT": adapterName,
	}
	if ctx.Config.Workspace.Name != "" {
		env["ADP_WORKSPACE"] = ctx.Config.Workspace.Name
	}
	if ctx.Config.Project.Root != "" {
		env["ADP_PROJECT_ROOT"] = ctx.Config.Project.Root
	}
	if ctx.GitRoot != "" {
		env["ADP_GIT_ROOT"] = ctx.GitRoot
	}
	if profile := EffectiveProfile(ctx); profile != "" {
		env["ADP_PROFILE"] = profile
	}
	if !ctx.Task.IsZero() {
		env["ADP_TASK_ID"] = ctx.Task.ID
		env["ADP_TASK_TITLE"] = ctx.Task.Title
		env["ADP_TASK_STATUS"] = ctx.Task.Status
		env["ADP_TASK_PRIORITY"] = ctx.Task.Priority
		env["ADP_TASK_PHASE"] = ctx.Task.Phase
		if strings.TrimSpace(ctx.Task.Owner) != "" {
			env["ADP_TASK_OWNER"] = ctx.Task.Owner
		}
		if !ctx.Task.ClaimedAt.IsZero() {
			env["ADP_TASK_CLAIMED_AT"] = formatTaskTime(ctx.Task.ClaimedAt)
		}
		if !ctx.Task.LeaseExpiresAt.IsZero() {
			env["ADP_TASK_LEASE_EXPIRES_AT"] = formatTaskTime(ctx.Task.LeaseExpiresAt)
		}
	}
	return env
}

func Launch(adapterName string, ctx api.Context, runtime api.RuntimeHandle, defaultCommand string, extraArgs []string) *api.LaunchSpec {
	env := make(map[string]string, len(runtime.Env)+6)
	for key, value := range runtime.Env {
		env[key] = value
	}
	for key, value := range RenderEnv(adapterName, ctx) {
		env[key] = value
	}
	if runtime.Root != "" {
		env["ADP_RUNTIME_ROOT"] = runtime.Root
	}
	if runtime.SessionID != "" {
		env["ADP_SESSION_ID"] = runtime.SessionID
	}
	if runtime.TaskID != "" {
		env["ADP_TASK_ID"] = runtime.TaskID
	}
	gitenv.RemoveRepositoryDirectives(env)

	command := strings.TrimSpace(ctx.Agent.Command)
	if command == "" {
		command = defaultCommand
	}

	args := append([]string(nil), extraArgs...)
	return &api.LaunchSpec{
		Command: command,
		Args:    args,
		Env:     env,
		Dir:     runtime.Root,
	}
}

func EffectiveProfile(ctx api.Context) string {
	if profile := strings.TrimSpace(ctx.Profile); profile != "" {
		return profile
	}
	if profile := strings.TrimSpace(ctx.Agent.Profile); profile != "" {
		return profile
	}
	return "default"
}

func writeWorkspace(b *strings.Builder, adapterName string, ctx api.Context) {
	b.WriteString("## Workspace\n\n")
	fmt.Fprintf(b, "- Name: %s\n", defaultText(ctx.Config.Workspace.Name, "unnamed"))
	fmt.Fprintf(b, "- Project root: %s\n", defaultText(ctx.Config.Project.Root, "not configured"))
	fmt.Fprintf(b, "- Agent: %s\n", adapterName)
	fmt.Fprintf(b, "- Profile: %s\n\n", EffectiveProfile(ctx))
}

func writeTask(b *strings.Builder, ctx api.Context) {
	if ctx.Task.IsZero() {
		return
	}

	b.WriteString("## Current Task\n\n")
	fmt.Fprintf(b, "- ID: %s\n", ctx.Task.ID)
	fmt.Fprintf(b, "- Title: %s\n", defaultText(ctx.Task.Title, "untitled"))
	fmt.Fprintf(b, "- Status: %s\n", defaultText(ctx.Task.Status, "unknown"))
	fmt.Fprintf(b, "- Priority: %s\n", defaultText(ctx.Task.Priority, "normal"))
	fmt.Fprintf(b, "- Phase: %s\n", defaultText(ctx.Task.Phase, "unassigned"))
	if strings.TrimSpace(ctx.Task.Owner) != "" {
		fmt.Fprintf(b, "- Owner: %s\n", strings.TrimSpace(ctx.Task.Owner))
	}
	if !ctx.Task.ClaimedAt.IsZero() {
		fmt.Fprintf(b, "- Claimed at: %s\n", formatTaskTime(ctx.Task.ClaimedAt))
	}
	if !ctx.Task.LeaseExpiresAt.IsZero() {
		fmt.Fprintf(b, "- Lease expires at: %s\n", formatTaskTime(ctx.Task.LeaseExpiresAt))
	}
	if strings.TrimSpace(ctx.Task.Description) != "" {
		fmt.Fprintf(b, "- Description: %s\n", strings.TrimSpace(ctx.Task.Description))
	}
	if strings.TrimSpace(ctx.Task.BlockedReason) != "" {
		fmt.Fprintf(b, "- Blocked reason: %s\n", strings.TrimSpace(ctx.Task.BlockedReason))
	}
	b.WriteByte('\n')
}

func writePlanningContract(b *strings.Builder, ctx api.Context) {
	workspace := shellQuote(defaultText(ctx.Config.Workspace.Name, "$ADP_WORKSPACE"))

	b.WriteString("## ADP Planning Contract\n\n")
	b.WriteString("ADP is the authoritative local planning and progress ledger for this workspace.\n")
	b.WriteString("Provider-native todo lists or task panels are scratch space only. They may mirror the active ADP task for visibility, but durable task state must be created and updated through ADP.\n\n")
	b.WriteString("Use the `ADP_CLI` environment variable when it is set. If it is missing, use `adp` from `PATH`.\n\n")
	b.WriteString("Durable task commands:\n")
	fmt.Fprintf(b, "- Inspect next work: `$ADP_CLI tasks next --workspace %s --format json`\n", workspace)
	fmt.Fprintf(b, "- Atomically take next work: `$ADP_CLI tasks take --workspace %s --owner <owner> --lease 4h --format json`\n", workspace)
	fmt.Fprintf(b, "- Inspect stale claims: `$ADP_CLI tasks stale --workspace %s --format json`\n", workspace)
	fmt.Fprintf(b, "- Create durable work: `$ADP_CLI tasks add --workspace %s --priority <priority> --phase <phase-id> --description <text> <title>`\n", workspace)
	fmt.Fprintf(b, "- Claim selected work: `$ADP_CLI tasks claim --workspace %s <task-id> --owner <owner> --lease 4h`\n", workspace)
	if ctx.Task.IsZero() {
		fmt.Fprintf(b, "- Update durable work: `$ADP_CLI tasks update --workspace %s <task-id> --status <status>`\n", workspace)
		fmt.Fprintf(b, "- Block durable work: `$ADP_CLI tasks block --workspace %s <task-id> --reason <reason>`\n", workspace)
		fmt.Fprintf(b, "- Complete durable work: `$ADP_CLI tasks done --workspace %s <task-id>`\n", workspace)
		fmt.Fprintf(b, "- Renew durable work: `$ADP_CLI tasks renew --workspace %s <task-id> --owner <owner> --lease 4h`\n", workspace)
		fmt.Fprintf(b, "- Release durable work: `$ADP_CLI tasks release --workspace %s <task-id> --owner <owner>`\n\n", workspace)
		return
	}
	b.WriteString("- Update this task: `$ADP_CLI tasks update --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\" --status <status>`\n")
	b.WriteString("- Block this task: `$ADP_CLI tasks block --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\" --reason <reason>`\n")
	b.WriteString("- Complete this task: `$ADP_CLI tasks done --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\"`\n")
	fmt.Fprintf(b, "- Renew this task: `$ADP_CLI tasks renew --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\" --owner %s --lease 4h`\n", currentTaskOwnerArg(ctx.Task))
	fmt.Fprintf(b, "- Release this task: `$ADP_CLI tasks release --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\" --owner %s`\n\n", currentTaskOwnerArg(ctx.Task))
}

func writeLeaseHandoff(b *strings.Builder, ctx api.Context) {
	workspace := shellQuote(defaultText(ctx.Config.Workspace.Name, "$ADP_WORKSPACE"))

	b.WriteString("## ADP Lease Handoff\n\n")
	if ctx.Task.IsZero() {
		b.WriteString("Before starting durable execution, inspect stale ADP claims and claim work through ADP so interrupted sessions are visible to other workers.\n")
		fmt.Fprintf(b, "- Inspect interrupted work: `$ADP_CLI tasks stale --workspace %s --format json`\n", workspace)
		fmt.Fprintf(b, "- Reclaim only through ADP ownership commands: `%s` or `%s`\n\n",
			fmt.Sprintf("$ADP_CLI tasks take --workspace %s --owner <owner> --lease 4h --format json", workspace),
			fmt.Sprintf("$ADP_CLI tasks claim --workspace %s <task-id> --owner <owner> --lease 4h", workspace),
		)
		return
	}

	b.WriteString("Keep this ADP task claim alive during long-running work. Renew before the lease expires, using the current ADP owner, and do not create duplicate provider-native tasks to recover interrupted work.\n")
	if !ctx.Task.LeaseExpiresAt.IsZero() {
		fmt.Fprintf(b, "- Current lease expires at: %s\n", formatTaskTime(ctx.Task.LeaseExpiresAt))
	}
	fmt.Fprintf(b, "- Renew active claim: `$ADP_CLI tasks renew --workspace \"$ADP_WORKSPACE\" \"$ADP_TASK_ID\" --owner %s --lease 4h`\n", currentTaskOwnerArg(ctx.Task))
	fmt.Fprintf(b, "- Inspect interrupted claims before taking over work: `$ADP_CLI tasks stale --workspace %s --format json`\n", workspace)
	fmt.Fprintf(b, "- Reclaim expired work only through ADP: `%s` or `%s`\n\n",
		fmt.Sprintf("$ADP_CLI tasks take --workspace %s --owner <owner> --lease 4h --format json", workspace),
		fmt.Sprintf("$ADP_CLI tasks claim --workspace %s <task-id> --owner <owner> --lease 4h", workspace),
	)
}

func writeGitBoundary(b *strings.Builder, ctx api.Context) {
	projectRoot := defaultText(ctx.Config.Project.Root, "$ADP_PROJECT_ROOT")
	workspace := shellQuote(defaultText(ctx.Config.Workspace.Name, "$ADP_WORKSPACE"))
	gitRoot := strings.TrimSpace(ctx.GitRoot)

	b.WriteString("## Git Boundary\n\n")
	b.WriteString("The ADP runtime root is not the authoritative Git working tree. Repository Git metadata is intentionally not exposed in the runtime overlay, so Git inspection or mutation must target the real project root explicitly.\n\n")
	fmt.Fprintf(b, "ADP neutralizes repository-directing Git environment variables before launch: `%s`. Normal shell environment and auth-related variables remain available.\n\n", strings.Join(gitenv.RepositoryDirectiveNames(), "`, `"))
	if gitRoot == "" {
		b.WriteString("No Git worktree root was detected for this project root, so `ADP_GIT_ROOT` may be unset. Inspect local diagnostics before assuming repository state.\n")
		fmt.Fprintf(b, "- Diagnose Git context: `$ADP_CLI workspace doctor %s --verbose`\n", workspace)
		fmt.Fprintf(b, "- Diagnose Git context as JSON: `$ADP_CLI workspace doctor %s --format json`\n\n", workspace)
	} else {
		fmt.Fprintf(b, "Detected Git worktree root: %s\n", gitRoot)
		if ctx.Config.Project.Root != "" && filepath.Clean(ctx.Config.Project.Root) != filepath.Clean(gitRoot) {
			b.WriteString("`ADP_PROJECT_ROOT` and `ADP_GIT_ROOT` differ. This usually means the configured project root is a subdirectory inside a larger Git worktree; keep project-scoped inspection on `ADP_PROJECT_ROOT`, and use `ADP_GIT_ROOT` only when you intentionally need whole-worktree context.\n")
			b.WriteString("Staging and committing still use the repository index for the whole worktree, so Git mutations must be deliberate and explicitly targeted.\n\n")
		} else {
			b.WriteString("`ADP_GIT_ROOT` matches `ADP_PROJECT_ROOT` for this runtime session.\n\n")
		}
	}
	b.WriteString("Use project-root Git commands:\n")
	b.WriteString("- Inspect status: `git -C \"$ADP_PROJECT_ROOT\" status --short --branch`\n")
	b.WriteString("- Inspect unstaged changes: `git -C \"$ADP_PROJECT_ROOT\" diff`\n")
	b.WriteString("- Inspect staged changes: `git -C \"$ADP_PROJECT_ROOT\" diff --cached`\n")
	if gitRoot != "" {
		b.WriteString("- Inspect whole-worktree status: `git -C \"$ADP_GIT_ROOT\" status --short --branch`\n")
	}
	b.WriteString("- For Git mutations, first `cd \"$ADP_PROJECT_ROOT\"` or use `git -C \"$ADP_PROJECT_ROOT\" ...` deliberately.\n\n")
	fmt.Fprintf(b, "Real project root: %s\n\n", projectRoot)
}

func writeTaskboxBridge(b *strings.Builder, ctx api.Context) {
	b.WriteString("## Tool Taskbox Bridge\n\n")
	if ctx.Task.IsZero() {
		b.WriteString("No ADP task is bound to this runtime session. Before doing durable work, inspect or create ADP tasks and claim the selected task through ADP.\n\n")
	} else {
		b.WriteString("When work starts, mirror the active ADP task into this tool's native task or todo panel if the tool provides one.\n")
		b.WriteString("Mirror at minimum the ADP task ID, title, status, phase, owner, lease expiration, and local subtasks so the tool panel shows the task that ADP assigned.\n")
		b.WriteString("Keep that panel aligned with the active ADP task for local visibility only; do not treat provider-native task state as authoritative.\n")
		b.WriteString("If the tool cannot expose a native task panel, continue using ADP commands as the durable task interface.\n\n")
	}
	b.WriteString("Do not sync provider-private todo state back into ADP automatically. Record durable progress explicitly through ADP commands and session evidence.\n\n")
}

func writePlanModeBridge(b *strings.Builder, ctx api.Context) {
	workspace := shellQuote(defaultText(ctx.Config.Workspace.Name, "$ADP_WORKSPACE"))

	b.WriteString("## Tool Plan Mode Bridge\n\n")
	b.WriteString("If this tool has a native plan mode, treat that plan as a proposal view. ADP remains the durable planning ledger.\n")
	b.WriteString("While in plan mode, do not edit project files, complete tasks, accept phases, commit, or push unless the user explicitly approves execution outside planning.\n\n")
	b.WriteString("Use ADP for durable planning handoff:\n")
	fmt.Fprintf(b, "- Preview structured planning input without writing the ledger: `$ADP_CLI plan preview --workspace %s --file - --format json`\n", workspace)
	fmt.Fprintf(b, "- Apply structured planning input only after explicit user or operator approval: `$ADP_CLI plan apply --workspace %s --file - --format json`\n", workspace)
	fmt.Fprintf(b, "- Inspect phase gates without changing them: `$ADP_CLI phase status --workspace %s --format json`\n\n", workspace)
	b.WriteString("Provider-native plan approval is not ADP phase acceptance. Persist accepted plans through ADP commands and report the resulting phase and task IDs.\n\n")
}

func currentTaskOwnerArg(task api.TaskContext) string {
	if strings.TrimSpace(task.Owner) == "" {
		return "<owner>"
	}
	return `"$ADP_TASK_OWNER"`
}

func formatTaskTime(value time.Time) string {
	return value.UTC().Format(time.RFC3339)
}

func writeSection(b *strings.Builder, title, body string) {
	fmt.Fprintf(b, "## %s\n\n", title)
	b.WriteString(strings.TrimSpace(body))
	b.WriteString("\n\n")
}

func memoryText(ctx api.Context) string {
	if !ctx.Config.Memory.Enabled {
		return "Shared memory is disabled for this workspace."
	}
	return readWorkspaceFile(ctx.WorkspaceDir, ctx.Config.Memory.Shared, "Shared memory is enabled, but no shared memory file is configured.")
}

func rulesText(ctx api.Context) string {
	if len(ctx.Config.Rules) == 0 {
		return "No workspace rules are configured."
	}

	keys := make([]string, 0, len(ctx.Config.Rules))
	for key := range ctx.Config.Rules {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	for _, key := range keys {
		fmt.Fprintf(&b, "- %s: %s\n", key, ctx.Config.Rules[key])
	}
	return b.String()
}

func mcpText(ctx api.Context) string {
	if !ctx.Config.MCP.Enabled {
		return "MCP is disabled for this workspace."
	}

	var b strings.Builder
	servers := append([]string(nil), ctx.Config.MCP.Servers...)
	sort.Strings(servers)
	if len(servers) == 0 {
		b.WriteString("Servers: none configured.\n\n")
	} else {
		b.WriteString("Servers:\n")
		for _, server := range servers {
			fmt.Fprintf(&b, "- %s\n", server)
		}
		b.WriteString("\n")
	}
	b.WriteString("Config:\n")
	b.WriteString(readWorkspaceFile(ctx.WorkspaceDir, ctx.Config.MCP.Config, "No MCP config file is configured."))
	return b.String()
}

func profileText(adapterName string, ctx api.Context) string {
	profile := EffectiveProfile(ctx)

	var b strings.Builder
	fmt.Fprintf(&b, "Name: %s\n", profile)
	fmt.Fprintf(&b, "Agent enabled: %t\n", ctx.Agent.Enabled)
	fmt.Fprintf(&b, "Agent command: %s\n", defaultText(ctx.Agent.Command, adapterName))
	if len(ctx.Agent.Options) > 0 {
		b.WriteString("Options:\n")
		keys := make([]string, 0, len(ctx.Agent.Options))
		for key := range ctx.Agent.Options {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(&b, "- %s: %s\n", key, ctx.Agent.Options[key])
		}
	}

	b.WriteString("\nProfile file:\n")
	b.WriteString(readProfileFile(ctx.WorkspaceDir, adapterName, profile))
	return b.String()
}

func readProfileFile(workspaceDir, adapterName, profile string) string {
	if profile != "" && profile != "default" {
		for _, ext := range []string{".md", ".yaml", ".yml", ".json"} {
			rel := filepath.Join("profiles", profile+ext)
			if text := readExistingWorkspaceFile(workspaceDir, rel); text != "" {
				return text
			}
		}
	}

	for _, ext := range []string{".md", ".yaml", ".yml", ".json"} {
		rel := filepath.Join("profiles", adapterName+ext)
		if text := readExistingWorkspaceFile(workspaceDir, rel); text != "" {
			return text
		}
	}

	return fmt.Sprintf("No profile file was found for profile %q or adapter %q; using the inline profile summary above.", profile, adapterName)
}

func readExistingWorkspaceFile(workspaceDir, rel string) string {
	full, ok := workspacePath(workspaceDir, rel)
	if !ok {
		return ""
	}
	data, err := os.ReadFile(full)
	if err != nil || len(data) == 0 {
		return ""
	}
	return string(data)
}

func readWorkspaceFile(workspaceDir, rel, emptyMessage string) string {
	rel = strings.TrimSpace(rel)
	if rel == "" {
		return emptyMessage
	}
	full, ok := workspacePath(workspaceDir, rel)
	if !ok {
		return fmt.Sprintf("Configured path %q is outside the ADP workspace directory; using default content.", rel)
	}
	data, err := os.ReadFile(full)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Sprintf("Configured file %q is missing; using default content.", filepath.Clean(rel))
		}
		return fmt.Sprintf("Configured file %q could not be read: %v. Using default content.", filepath.Clean(rel), err)
	}
	if len(data) == 0 {
		return fmt.Sprintf("Configured file %q is empty; using default content.", filepath.Clean(rel))
	}
	return string(data)
}

func workspacePath(workspaceDir, rel string) (string, bool) {
	if strings.TrimSpace(workspaceDir) == "" || filepath.IsAbs(rel) {
		return "", false
	}
	clean := filepath.Clean(rel)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", false
	}
	return filepath.Join(workspaceDir, clean), true
}

func quote(value string) string {
	return strconv.Quote(value)
}

func ctxString(value string) string {
	return strings.TrimSpace(value)
}

func defaultText(value, fallback string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return fallback
	}
	return value
}

func shellQuote(value string) string {
	if strings.HasPrefix(value, "$") {
		return value
	}
	return strconv.Quote(value)
}
