package shell

import (
	"strings"

	"github.com/karoc/adp/internal/commandmeta"
)

func renderBashCompletion(commandName string) string {
	functionName := completionFunctionName(commandName)
	workspaceHelperName := functionName + "_selected_workspace"
	dynamicHelperName := functionName + "_dynamic_values"

	var out strings.Builder
	out.WriteString("# bash completion for ")
	out.WriteString(commandName)
	out.WriteByte('\n')
	writeDynamicCompletionEndpointComments(&out, commandName)
	out.WriteString(workspaceHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal i\n")
	out.WriteString("\tfor (( i=1; i<COMP_CWORD; i++ )); do\n")
	out.WriteString("\t\tif [ \"${COMP_WORDS[i]}\" = \"--workspace\" ] || [ \"${COMP_WORDS[i]}\" = \"-w\" ]; then\n")
	out.WriteString("\t\t\tprintf '%s\\n' \"${COMP_WORDS[i+1]}\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\tfi\n")
	out.WriteString("\tdone\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString(dynamicHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal kind selected_workspace prefix value\n")
	out.WriteString("\tkind=\"$1\"\n")
	out.WriteString("\tselected_workspace=\"$2\"\n")
	out.WriteString("\tprefix=\"$3\"\n")
	out.WriteString("\tif [ \"$kind\" = \"profiles\" -o \"$kind\" = \"tasks\" -o \"$kind\" = \"phases\" -o \"$kind\" = \"sessions\" -o \"$kind\" = \"owners\" ] && [ -n \"$selected_workspace\" ]; then\n")
	out.WriteString("\t\twhile IFS= read -r value; do\n")
	out.WriteString("\t\t\tcase \"$value\" in \"$prefix\"*) COMPREPLY+=( \"$value\" ) ;; esac\n")
	out.WriteString("\t\tdone < <(")
	out.WriteString(commandName)
	out.WriteString(" completion values \"$kind\" --workspace \"$selected_workspace\" 2>/dev/null)\n")
	out.WriteString("\telse\n")
	out.WriteString("\t\twhile IFS= read -r value; do\n")
	out.WriteString("\t\t\tcase \"$value\" in \"$prefix\"*) COMPREPLY+=( \"$value\" ) ;; esac\n")
	out.WriteString("\t\tdone < <(")
	out.WriteString(commandName)
	out.WriteString(" completion values \"$kind\" 2>/dev/null)\n")
	out.WriteString("\tfi\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString(functionName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal cur prev command subcommand selected_workspace\n")
	out.WriteString("\tCOMPREPLY=()\n")
	out.WriteString("\tcur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	out.WriteString("\tprev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	out.WriteString("\tcommand=\"${COMP_WORDS[1]}\"\n")
	out.WriteString("\tsubcommand=\"${COMP_WORDS[2]}\"\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"$prev\" in\n")
	out.WriteString("\t\t--workspace|-w)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--profile|-p)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" profiles \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--agent)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" agents \"\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--task)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" tasks \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--phase)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" phases \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--owner)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" owners \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--status)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" statuses \"\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--session)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" sessions \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--shell|-s)\n")
	out.WriteString("\t\t\tif [ \"$command\" = \"shell-hook\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.HookShells))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.CompletionShells))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--type)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.EventTypes))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--older-than)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.RuntimeAges))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--format)\n")
	out.WriteString("\t\t\tif [ \"$command\" = \"progress\" ] && [ \"$subcommand\" = \"report\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.MarkdownJSONFormats))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.TextJSONFormats))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--language)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.Languages))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteByte('\n')
	out.WriteString("\tif [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	out.WriteString("\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.RootCommandNames(), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\treturn 0\n")
	out.WriteString("\tfi\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"$command\" in\n")
	out.WriteString("\t\tdoctor)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tworkspace)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("workspace"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$COMP_CWORD\" -eq 3 ] && [ \"$subcommand\" = \"show\" -o \"$subcommand\" = \"remove\" -o \"$subcommand\" = \"rename\" -o \"$subcommand\" = \"doctor\" ]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenter)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("enter"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenv)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("env"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tshell-hook)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("shell-hook"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tcompletion)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashWords(completionTopValues()))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"values\" ] && [ \"$COMP_CWORD\" -eq 3 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.CompletionKinds))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"values\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashWords(completionValuesOptions()))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashWords(completionRootOptions()))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tevents)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("events"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"list\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("events"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tsessions)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("sessions"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$cur\" = -* ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("sessions"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"show\" -o \"$subcommand\" = \"restore-plan\" ]; then\n")
	out.WriteString("\t\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" sessions \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"list\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("sessions"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\truntime)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("runtime"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"prune\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("runtime"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\ttasks)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("tasks"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$cur\" = -* ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("tasks"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"show\" -o \"$subcommand\" = \"update\" -o \"$subcommand\" = \"claim\" -o \"$subcommand\" = \"release\" -o \"$subcommand\" = \"done\" -o \"$subcommand\" = \"block\" ]; then\n")
	out.WriteString("\t\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" tasks \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("tasks"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tplan)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("plan"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("plan"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tphase)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("phase"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$cur\" = -* ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("phase"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"show\" -o \"$subcommand\" = \"start\" -o \"$subcommand\" = \"accept\" -o \"$subcommand\" = \"commit\" -o \"$subcommand\" = \"push\" ]; then\n")
	out.WriteString("\t\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" phases \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("phase"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tprogress)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashProgressTopWords())
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("progress"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\trun)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" agents \"\" \"$cur\"\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("run"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString("complete -F ")
	out.WriteString(functionName)
	out.WriteByte(' ')
	out.WriteString(commandName)
	out.WriteByte('\n')
	return out.String()
}
