package shell

import (
	"strings"

	"github.com/karoc/adp/internal/commandmeta"
)

func renderZshCompletion(commandName string) string {
	functionName := completionFunctionName(commandName)
	workspaceHelperName := functionName + "_selected_workspace"
	workspaceValuesName := functionName + "_workspace_values"
	profileValuesName := functionName + "_profile_values"
	agentValuesName := functionName + "_agent_values"
	dynamicValuesName := functionName + "_dynamic_values"

	var out strings.Builder
	out.WriteString("#compdef ")
	out.WriteString(commandName)
	out.WriteString("\n")
	writeDynamicCompletionEndpointComments(&out, commandName)
	out.WriteString(workspaceHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal i\n")
	out.WriteString("\tfor (( i=1; i<CURRENT; i++ )); do\n")
	out.WriteString("\t\tif [[ \"${words[i]}\" == \"--workspace\" || \"${words[i]}\" == \"-w\" ]]; then\n")
	out.WriteString("\t\t\tprint -r -- \"${words[i+1]}\"\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\tfi\n")
	out.WriteString("\tdone\n")
	out.WriteString("}\n\n")
	out.WriteString(workspaceValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values workspaces 2>/dev/null)\"} )\n")
	out.WriteString("\t_describe -t workspaces 'workspace' values\n")
	out.WriteString("}\n\n")
	out.WriteString(profileValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal selected_workspace\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\tif [[ -n \"$selected_workspace\" ]]; then\n")
	out.WriteString("\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles --workspace \"$selected_workspace\" 2>/dev/null)\"} )\n")
	out.WriteString("\telse\n")
	out.WriteString("\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles 2>/dev/null)\"} )\n")
	out.WriteString("\tfi\n")
	out.WriteString("\t_describe -t profiles 'profile' values\n")
	out.WriteString("}\n\n")
	out.WriteString(agentValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values agents 2>/dev/null)\"} )\n")
	out.WriteString("\t_describe -t agents 'agent' values\n")
	out.WriteString("}\n\n")
	out.WriteString(dynamicValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal kind selected_workspace\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tkind=\"$1\"\n")
	out.WriteString("\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\tcase \"$kind\" in\n")
	out.WriteString("\t\tprofiles|tasks|phases|sessions|owners)\n")
	out.WriteString("\t\t\tif [[ -n \"$selected_workspace\" ]]; then\n")
	out.WriteString("\t\t\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values \"$kind\" --workspace \"$selected_workspace\" 2>/dev/null)\"} )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values \"$kind\" 2>/dev/null)\"} )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t*)\n")
	out.WriteString("\t\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values \"$kind\" 2>/dev/null)\"} )\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteString("\t_describe -t \"$kind\" \"$kind\" values\n")
	out.WriteString("}\n\n")
	out.WriteString(functionName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal -a commands workspace_commands events_commands sessions_commands runtime_commands tasks_commands plan_commands phase_commands\n")
	out.WriteString("\tcommands=(\n")
	out.WriteString(zshRootCommandEntries())
	out.WriteString("\t)\n")
	out.WriteString(zshArray("workspace_commands", commandmeta.SubcommandNames("workspace")))
	out.WriteString(zshArray("events_commands", commandmeta.SubcommandNames("events")))
	out.WriteString(zshArray("sessions_commands", commandmeta.SubcommandNames("sessions")))
	out.WriteString(zshArray("runtime_commands", commandmeta.SubcommandNames("runtime")))
	out.WriteString(zshArray("tasks_commands", commandmeta.SubcommandNames("tasks")))
	out.WriteString(zshArray("plan_commands", commandmeta.SubcommandNames("plan")))
	out.WriteString(zshArray("phase_commands", commandmeta.SubcommandNames("phase")))
	out.WriteByte('\n')
	out.WriteString("\tcase \"${words[CURRENT-1]}\" in\n")
	out.WriteString("\t\t--workspace|-w)\n")
	out.WriteString("\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--profile|-p)\n")
	out.WriteString("\t\t\t")
	out.WriteString(profileValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--agent)\n")
	out.WriteString("\t\t\t")
	out.WriteString(agentValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--task)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" tasks\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--phase)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" phases\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--owner)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" owners\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--status)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" statuses\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--session)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" sessions\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--shell|-s)\n")
	out.WriteString("\t\t\tif [[ \"${words[2]}\" == \"shell-hook\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("shell", commandmeta.HookShells))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("shell", commandmeta.CompletionShells))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--type)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("event type", commandmeta.EventTypes))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--older-than)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("runtime age", commandmeta.RuntimeAges))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--language)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("language", commandmeta.Languages))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--format)\n")
	out.WriteString("\t\t\tif [[ \"${words[2]}\" == \"progress\" && \"${words[3]}\" == \"report\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("format", commandmeta.MarkdownJSONFormats))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("format", commandmeta.TextJSONFormats))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteByte('\n')
	out.WriteString("\tif (( CURRENT == 2 )); then\n")
	out.WriteString("\t\t_describe -t commands 'adp command' commands\n")
	out.WriteString("\t\treturn\n")
	out.WriteString("\tfi\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"${words[2]}\" in\n")
	out.WriteString("\t\tdoctor)\n")
	out.WriteString("\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tworkspace)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t workspace-commands 'workspace command' workspace_commands\n")
	out.WriteString("\t\t\telif (( CURRENT == 4 )) && [[ \"${words[3]}\" == \"show\" || \"${words[3]}\" == \"remove\" || \"${words[3]}\" == \"rename\" || \"${words[3]}\" == \"doctor\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenter)\n")
	out.WriteString("\t\t\tif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("enter option", commandmeta.Options("enter")))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenv)\n")
	out.WriteString("\t\t\tif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("env option", commandmeta.Options("env")))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tshell-hook)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("shell-hook option", commandmeta.Options("shell-hook")))
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tcompletion)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion command", completionTopValues()))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"values\" && CURRENT == 4 ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion values kind", commandmeta.CompletionKinds))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"values\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion values option", completionValuesOptions()))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion option", completionRootOptions()))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tevents)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t events-commands 'events command' events_commands\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"list\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("events list option", commandmeta.Options("events")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tsessions)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t sessions-commands 'sessions command' sessions_commands\n")
	out.WriteString("\t\t\telif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("sessions option", commandmeta.Options("sessions")))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"show\" || \"${words[3]}\" == \"restore-plan\" || \"${words[3]}\" == \"resume-plan\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" sessions\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"list\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("sessions list option", commandmeta.Options("sessions")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\truntime)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t runtime-commands 'runtime command' runtime_commands\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"prune\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("runtime prune option", commandmeta.Options("runtime")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\ttasks)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t tasks-commands 'tasks command' tasks_commands\n")
	out.WriteString("\t\t\telif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("tasks option", commandmeta.Options("tasks")))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"show\" || \"${words[3]}\" == \"update\" || \"${words[3]}\" == \"claim\" || \"${words[3]}\" == \"release\" || \"${words[3]}\" == \"done\" || \"${words[3]}\" == \"block\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" tasks\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("tasks option", commandmeta.Options("tasks")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tplan)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t plan-commands 'plan command' plan_commands\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("plan option", commandmeta.Options("plan")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tphase)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t phase-commands 'phase command' phase_commands\n")
	out.WriteString("\t\t\telif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("phase option", commandmeta.Options("phase")))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"show\" || \"${words[3]}\" == \"start\" || \"${words[3]}\" == \"accept\" || \"${words[3]}\" == \"commit\" || \"${words[3]}\" == \"push\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicValuesName)
	out.WriteString(" phases\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("phase option", commandmeta.Options("phase")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tprogress)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("progress command", progressTopValues()))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("progress option", commandmeta.Options("progress")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\trun)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(agentValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("run option", commandmeta.Options("run")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString("compdef ")
	out.WriteString(functionName)
	out.WriteByte(' ')
	out.WriteString(commandName)
	out.WriteByte('\n')
	return out.String()
}
