package shell

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/karoc/adp/internal/commandmeta"
)

const (
	defaultCompletionShell       = "bash"
	defaultCompletionCommandName = "adp"
)

var (
	ErrUnsupportedCompletionShell   = errors.New("unsupported shell for completion")
	ErrInvalidCompletionCommandName = errors.New("invalid shell completion command name")
)

type CompletionOptions struct {
	Shell       string
	CommandName string
}

func RenderCompletion(opts CompletionOptions) (string, error) {
	shellName := normalizeCompletionShell(opts.Shell)
	if !isSupportedCompletionShell(shellName) {
		return "", fmt.Errorf("%w: %s", ErrUnsupportedCompletionShell, opts.Shell)
	}

	commandName := opts.CommandName
	if commandName == "" {
		commandName = defaultCompletionCommandName
	}
	if !isValidCompletionCommandName(commandName) {
		return "", fmt.Errorf("%w: %s", ErrInvalidCompletionCommandName, commandName)
	}

	switch shellName {
	case "bash":
		return renderBashCompletion(commandName), nil
	case "zsh":
		return renderZshCompletion(commandName), nil
	default:
		return "", fmt.Errorf("%w: %s", ErrUnsupportedCompletionShell, opts.Shell)
	}
}

func renderBashCompletion(commandName string) string {
	functionName := completionFunctionName(commandName)
	workspaceHelperName := functionName + "_selected_workspace"
	dynamicHelperName := functionName + "_dynamic_values"

	var out strings.Builder
	out.WriteString("# bash completion for ")
	out.WriteString(commandName)
	out.WriteByte('\n')
	out.WriteString(workspaceHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal i\n")
	out.WriteString("\tfor (( i=1; i<COMP_CWORD; i++ )); do\n")
	out.WriteString("\t\tif [ \"${COMP_WORDS[i]}\" = \"--workspace\" ] || [ \"${COMP_WORDS[i]}\" = \"-w\" ]; then\n")
	out.WriteString("\t\t\tprintf '%s\\n' \"${COMP_WORDS[i+1]}\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\tfi\n")
	out.WriteString("\tdone\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString(dynamicHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal kind selected_workspace prefix value\n")
	out.WriteString("\tkind=\"$1\"\n")
	out.WriteString("\tselected_workspace=\"$2\"\n")
	out.WriteString("\tprefix=\"$3\"\n")
	out.WriteString("\tif [ \"$kind\" = \"profiles\" ] && [ -n \"$selected_workspace\" ]; then\n")
	out.WriteString("\t\twhile IFS= read -r value; do\n")
	out.WriteString("\t\t\tcase \"$value\" in \"$prefix\"*) COMPREPLY+=( \"$value\" ) ;; esac\n")
	out.WriteString("\t\tdone < <(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles --workspace \"$selected_workspace\" 2>/dev/null)\n")
	out.WriteString("\telif [ \"$kind\" = \"profiles\" ]; then\n")
	out.WriteString("\t\twhile IFS= read -r value; do\n")
	out.WriteString("\t\t\tcase \"$value\" in \"$prefix\"*) COMPREPLY+=( \"$value\" ) ;; esac\n")
	out.WriteString("\t\tdone < <(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles 2>/dev/null)\n")
	out.WriteString("\telse\n")
	out.WriteString("\t\twhile IFS= read -r value; do\n")
	out.WriteString("\t\t\tcase \"$value\" in \"$prefix\"*) COMPREPLY+=( \"$value\" ) ;; esac\n")
	out.WriteString("\t\tdone < <(")
	out.WriteString(commandName)
	out.WriteString(" completion values workspaces 2>/dev/null)\n")
	out.WriteString("\tfi\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString(functionName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal cur prev command subcommand selected_workspace\n")
	out.WriteString("\tCOMPREPLY=()\n")
	out.WriteString("\tcur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	out.WriteString("\tprev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	out.WriteString("\tcommand=\"${COMP_WORDS[1]}\"\n")
	out.WriteString("\tsubcommand=\"${COMP_WORDS[2]}\"\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"$prev\" in\n")
	out.WriteString("\t\t--workspace|-w)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--profile|-p)\n")
	out.WriteString("\t\t\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" profiles \"$selected_workspace\" \"$cur\"\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--shell|-s)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.Shells))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--type)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.EventTypes))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--older-than)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.RuntimeAges))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--format)\n")
	out.WriteString("\t\t\tif [ \"$command\" = \"progress\" ] && [ \"$subcommand\" = \"report\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.MarkdownJSONFormats))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.TextJSONFormats))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--language)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.Languages))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\treturn 0\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteByte('\n')
	out.WriteString("\tif [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	out.WriteString("\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.RootCommandNames(), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\treturn 0\n")
	out.WriteString("\tfi\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"$command\" in\n")
	out.WriteString("\t\tdoctor)\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tworkspace)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("workspace"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$COMP_CWORD\" -eq 3 ] && [ \"$subcommand\" = \"show\" -o \"$subcommand\" = \"remove\" -o \"$subcommand\" = \"rename\" -o \"$subcommand\" = \"doctor\" ]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenter)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("enter"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenv)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("env"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t")
	out.WriteString(dynamicHelperName)
	out.WriteString(" workspaces \"\" \"$cur\"\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tshell-hook)\n")
	out.WriteString("\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("shell-hook"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tcompletion)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashWords(commandmeta.CommandValues("completion")))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"values\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(commandmeta.ShellWords(commandmeta.CompletionKinds))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("completion"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tevents)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("events"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"list\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("events"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tsessions)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("sessions"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"list\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("sessions"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\truntime)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("runtime"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telif [ \"$subcommand\" = \"prune\" ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("runtime"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\ttasks)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("tasks"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("tasks"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tplan)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("plan"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("plan"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tphase)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("phase"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("phase"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tprogress)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(bashProgressTopWords())
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("progress"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\trun)\n")
	out.WriteString("\t\t\tif [ \"$COMP_CWORD\" -eq 2 ]; then\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.SubcommandNames("run"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\tCOMPREPLY=( $(compgen -W \"")
	out.WriteString(strings.Join(commandmeta.OptionNames("run"), " "))
	out.WriteString("\" -- \"$cur\") )\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString("complete -F ")
	out.WriteString(functionName)
	out.WriteByte(' ')
	out.WriteString(commandName)
	out.WriteByte('\n')
	return out.String()
}

func renderZshCompletion(commandName string) string {
	functionName := completionFunctionName(commandName)
	workspaceHelperName := functionName + "_selected_workspace"
	workspaceValuesName := functionName + "_workspace_values"
	profileValuesName := functionName + "_profile_values"

	var out strings.Builder
	out.WriteString("#compdef ")
	out.WriteString(commandName)
	out.WriteString("\n\n")
	out.WriteString(workspaceHelperName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal i\n")
	out.WriteString("\tfor (( i=1; i<CURRENT; i++ )); do\n")
	out.WriteString("\t\tif [[ \"${words[i]}\" == \"--workspace\" || \"${words[i]}\" == \"-w\" ]]; then\n")
	out.WriteString("\t\t\tprint -r -- \"${words[i+1]}\"\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\tfi\n")
	out.WriteString("\tdone\n")
	out.WriteString("}\n\n")
	out.WriteString(workspaceValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values workspaces 2>/dev/null)\"} )\n")
	out.WriteString("\t_describe -t workspaces 'workspace' values\n")
	out.WriteString("}\n\n")
	out.WriteString(profileValuesName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal selected_workspace\n")
	out.WriteString("\tlocal -a values\n")
	out.WriteString("\tselected_workspace=\"$(")
	out.WriteString(workspaceHelperName)
	out.WriteString(")\"\n")
	out.WriteString("\tif [[ -n \"$selected_workspace\" ]]; then\n")
	out.WriteString("\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles --workspace \"$selected_workspace\" 2>/dev/null)\"} )\n")
	out.WriteString("\telse\n")
	out.WriteString("\t\tvalues=( ${(f)\"$(")
	out.WriteString(commandName)
	out.WriteString(" completion values profiles 2>/dev/null)\"} )\n")
	out.WriteString("\tfi\n")
	out.WriteString("\t_describe -t profiles 'profile' values\n")
	out.WriteString("}\n\n")
	out.WriteString(functionName)
	out.WriteString("() {\n")
	out.WriteString("\tlocal -a commands workspace_commands events_commands sessions_commands runtime_commands tasks_commands plan_commands phase_commands run_agents\n")
	out.WriteString("\tcommands=(\n")
	out.WriteString(zshRootCommandEntries())
	out.WriteString("\t)\n")
	out.WriteString(zshArray("workspace_commands", commandmeta.SubcommandNames("workspace")))
	out.WriteString(zshArray("events_commands", commandmeta.SubcommandNames("events")))
	out.WriteString(zshArray("sessions_commands", commandmeta.SubcommandNames("sessions")))
	out.WriteString(zshArray("runtime_commands", commandmeta.SubcommandNames("runtime")))
	out.WriteString(zshArray("tasks_commands", commandmeta.SubcommandNames("tasks")))
	out.WriteString(zshArray("plan_commands", commandmeta.SubcommandNames("plan")))
	out.WriteString(zshArray("phase_commands", commandmeta.SubcommandNames("phase")))
	out.WriteString(zshArray("run_agents", commandmeta.SubcommandNames("run")))
	out.WriteByte('\n')
	out.WriteString("\tcase \"${words[CURRENT-1]}\" in\n")
	out.WriteString("\t\t--workspace|-w)\n")
	out.WriteString("\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--profile|-p)\n")
	out.WriteString("\t\t\t")
	out.WriteString(profileValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--shell|-s)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("shell", commandmeta.Shells))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--type)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("event type", commandmeta.EventTypes))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--older-than)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("runtime age", commandmeta.RuntimeAges))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--language)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("language", commandmeta.Languages))
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\t--format)\n")
	out.WriteString("\t\t\tif [[ \"${words[2]}\" == \"progress\" && \"${words[3]}\" == \"report\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("format", commandmeta.MarkdownJSONFormats))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("format", commandmeta.TextJSONFormats))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\treturn\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteByte('\n')
	out.WriteString("\tif (( CURRENT == 2 )); then\n")
	out.WriteString("\t\t_describe -t commands 'adp command' commands\n")
	out.WriteString("\t\treturn\n")
	out.WriteString("\tfi\n")
	out.WriteByte('\n')
	out.WriteString("\tcase \"${words[2]}\" in\n")
	out.WriteString("\t\tdoctor)\n")
	out.WriteString("\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tworkspace)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t workspace-commands 'workspace command' workspace_commands\n")
	out.WriteString("\t\t\telif (( CURRENT == 4 )) && [[ \"${words[3]}\" == \"show\" || \"${words[3]}\" == \"remove\" || \"${words[3]}\" == \"rename\" || \"${words[3]}\" == \"doctor\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenter)\n")
	out.WriteString("\t\t\tif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("enter option", commandmeta.Options("enter")))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tenv)\n")
	out.WriteString("\t\t\tif [[ \"$PREFIX\" == -* ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("env option", commandmeta.Options("env")))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(workspaceValuesName)
	out.WriteString("\n")
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tshell-hook)\n")
	out.WriteString("\t\t\t")
	out.WriteString(zshValues("shell-hook option", commandmeta.Options("shell-hook")))
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tcompletion)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion command", commandmeta.CommandValues("completion")))
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"values\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion values kind", commandmeta.CompletionKinds))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("completion option", commandmeta.Options("completion")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tevents)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t events-commands 'events command' events_commands\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"list\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("events list option", commandmeta.Options("events")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tsessions)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t sessions-commands 'sessions command' sessions_commands\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"list\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("sessions list option", commandmeta.Options("sessions")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\truntime)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t runtime-commands 'runtime command' runtime_commands\n")
	out.WriteString("\t\t\telif [[ \"${words[3]}\" == \"prune\" ]]; then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("runtime prune option", commandmeta.Options("runtime")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\ttasks)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t tasks-commands 'tasks command' tasks_commands\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("tasks option", commandmeta.Options("tasks")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tplan)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t plan-commands 'plan command' plan_commands\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("plan option", commandmeta.Options("plan")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tphase)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t phase-commands 'phase command' phase_commands\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("phase option", commandmeta.Options("phase")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\tprogress)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("progress command", progressTopValues()))
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("progress option", commandmeta.Options("progress")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\t\trun)\n")
	out.WriteString("\t\t\tif (( CURRENT == 3 )); then\n")
	out.WriteString("\t\t\t\t_describe -t agents 'agent' run_agents\n")
	out.WriteString("\t\t\telse\n")
	out.WriteString("\t\t\t\t")
	out.WriteString(zshValues("run option", commandmeta.Options("run")))
	out.WriteString("\t\t\tfi\n")
	out.WriteString("\t\t\t;;\n")
	out.WriteString("\tesac\n")
	out.WriteString("}\n")
	out.WriteByte('\n')
	out.WriteString("compdef ")
	out.WriteString(functionName)
	out.WriteByte(' ')
	out.WriteString(commandName)
	out.WriteByte('\n')
	return out.String()
}

func normalizeCompletionShell(shellName string) string {
	shellName = strings.TrimSpace(shellName)
	if shellName == "" {
		return defaultCompletionShell
	}

	shellName = filepath.Base(shellName)
	shellName = strings.TrimLeft(shellName, "-")
	shellName = strings.ToLower(shellName)
	return strings.TrimSuffix(shellName, ".exe")
}

func isSupportedCompletionShell(shellName string) bool {
	switch shellName {
	case "bash", "zsh":
		return true
	default:
		return false
	}
}

func isValidCompletionCommandName(commandName string) bool {
	if commandName == "" || isShellReservedWord(commandName) {
		return false
	}

	for index, r := range commandName {
		if index == 0 {
			if !isShellNameStart(r) {
				return false
			}
			continue
		}
		if r != '-' && !isShellNamePart(r) {
			return false
		}
	}
	return true
}

func completionFunctionName(commandName string) string {
	return "_" + strings.ReplaceAll(commandName, "-", "_") + "_completion"
}
